CREATE DATABASE RECOGNITION_SYSTEM IF NOT EXISTS;

CREATE TABLE USERS(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FISTNAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(35) NOT NULL
);


CREATE TABLE ADDRESS(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_USER INTEGER NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    RESIDENCE_NUMBER VARCHAR(6) NOT NULL,
    NEIGHBORHOOD VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(50) NOT NULL
);